pipeline{
    agent any
    
        stages{
            stage('Build-System details'){
                steps{
                    sh '''
                    echo '"SYSTEM DETAILS"'
                    uname -a
                    '''
                }
            }
            stage('Build-Memory details'){
                steps{
                    sh '''
                    echo "MEMORY DETAILS"
                    free -h
                    '''
                }
            }
            stage('Build-CPU details'){
                steps{
                    sh '''
                    echo "CPU DETAILS"
                    lscpu
                    '''
                }
            } 
        }
}