pipeline{
    agent{
        label 'dev'
    }
    
        stages{
            stage('Build-System details'){
                steps{
                    sh '''
                    echo '"SYSTEM DETAILS"'
                    uname -a
                    '''
                }
            }
            stage('Build-Memory details'){
                steps{
                    sh '''
                    echo "MEMORY DETAILS"
                    free -h
                    '''
                }
            }  
            stage('Hostname'){
                steps{
                    sh '''
                    echo "hostname"
                    hostname
                    '''
                }
            }
                stage('Path Details'){
                steps{
                    sh '''
                    echo "path"
                    pwd
                    '''
                }
            }

        }
}